// This is the user data from github authentication
const sampleData = {
  id: '85081368',
  displayName: null,
  username: 'tomahawk-jupiter',
  profileUrl: 'https://github.com/tomahawk-jupiter',
  photos: [ { value: 'https://avatars.githubusercontent.com/u/85081368?v=4' } ],
  provider: 'github',
  _raw: '{"login":"tomahawk-jupiter","id":85081368,"node_id":"MDQ6VXNlcjg1MDgxMzY4","avatar_url":"https://avatars.githubusercontent.com/u/85081368?v=4","gravatar_id":"","url":"https://api.github.com/users/tomahawk-jupiter","html_url":"https://github.com/tomahawk-jupiter","followers_url":"https://api.github.com/users/tomahawk-jupiter/followers","following_url":"https://api.github.com/users/tomahawk-jupiter/following{/other_user}","gists_url":"https://api.github.com/users/tomahawk-jupiter/gists{/gist_id}","starred_url":"https://api.github.com/users/tomahawk-jupiter/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tomahawk-jupiter/subscriptions","organizations_url":"https://api.github.com/users/tomahawk-jupiter/orgs","repos_url":"https://api.github.com/users/tomahawk-jupiter/repos","events_url":"https://api.github.com/users/tomahawk-jupiter/events{/privacy}","received_events_url":"https://api.github.com/users/tomahawk-jupiter/received_events","type":"User","site_admin":false,"name":null,"company":null,"blog":"","location":null,"email":null,"hireable":null,"bio":null,"twitter_username":null,"public_repos":21,"public_gists":0,"followers":0,"following":0,"created_at":"2021-05-30T21:14:45Z","updated_at":"2021-12-16T18:51:49Z"}',
  _json: {
    login: 'tomahawk-jupiter',
    id: 85081368,
    node_id: 'MDQ6VXNlcjg1MDgxMzY4',
    avatar_url: 'https://avatars.githubusercontent.com/u/85081368?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/tomahawk-jupiter',
    html_url: 'https://github.com/tomahawk-jupiter',
    followers_url: 'https://api.github.com/users/tomahawk-jupiter/followers',
    following_url: 'https://api.github.com/users/tomahawk-jupiter/following{/other_user}',
    gists_url: 'https://api.github.com/users/tomahawk-jupiter/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/tomahawk-jupiter/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/tomahawk-jupiter/subscriptions',
    organizations_url: 'https://api.github.com/users/tomahawk-jupiter/orgs',
    repos_url: 'https://api.github.com/users/tomahawk-jupiter/repos',
    events_url: 'https://api.github.com/users/tomahawk-jupiter/events{/privacy}',
    received_events_url: 'https://api.github.com/users/tomahawk-jupiter/received_events',
    type: 'User',
    site_admin: false,
    name: null,
    company: null,
    blog: '',
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 21,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: '2021-05-30T21:14:45Z',
    updated_at: '2021-12-16T18:51:49Z'
  }
}